name: Welcome New Contributors

on:
  pull_request_target:
    types: [opened]

permissions:
  pull-requests: write

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: Greet the contributor
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.payload.pull_request.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Thanks for contributing! 🚀 We'll review your pull request soon."
            })
